architecture: YOLOv4
use_gpu: true
max_iters: 240200
log_smooth_window: 20
log_iter: 500
save_dir: output
snapshot_iter: 20000
metric: traffic
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams
weights: output/yolov4_cspdarknet/model_final
num_classes: 19
use_fine_grained_loss: true
save_prediction_only: true

YOLOv4:
  backbone: CSPDarkNet
  yolo_head: YOLOv4Head

CSPDarkNet:
  norm_type: bn
  norm_decay: 0.
  depth: 53

YOLOv4Head:
  anchors: [[8, 8], [11, 11], [14, 14], [20, 20], [26, 26],
            [32, 32], [40, 40], [48, 48], [55, 55]]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  nms:
    background_label: -1
    keep_top_k: -1
    nms_threshold: 0.45
    nms_top_k: -1
    normalized: true
    score_threshold: 0.01
  downsample: [8,16,32]

YOLOv3Loss:
  # batch_size here is only used for fine grained loss, not used
  # for training batch_size setting, training batch_size setting
  # is in configs/yolov3_reader.yml TrainReader.batch_size, batch
  # size here should be set as same value as TrainReader.batch_size
  batch_size: 4
  ignore_thresh: 0.7
  label_smooth: true
  downsample: [8,16,32]
  #scale_x_y: [1.2, 1.1, 1.05]
  iou_loss: IouLoss
  match_score: true

IouLoss:
  loss_weight: 1.7
  max_height: 800
  max_width: 800
  ciou_term: true
  loss_square: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.2
    milestones:
    - 240000
    - 280000
    - 320000
  - !LinearWarmup
    start_factor: 0.
    steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 10.
  optimizer:
    momentum: 0.949
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 90
  dataset:
    !TrafficDataSet
      image_dir: test/pic/
      anno_path: test/input
      dataset_dir: ../../data_0/traffic_data/base_data
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 800
      interp: 1
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

TestReader:
  dataset:
    !ImageFolder
    use_default_label: true
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 800
      interp: 1
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
